Reverting the behvior when slave starts with initialized database
Fixes: https://github.com/sclorg/mysql-container/issues/226

diff --git a/root-common/usr/bin/run-mysqld-slave b/root-common/usr/bin/run-mysqld-slave
--- a/root-common/usr/bin/run-mysqld-slave
+++ b/root-common/usr/bin/run-mysqld-slave
@@ -14,11 +14,6 @@ export_setting_variables
 
 log_volume_info $MYSQL_DATADIR
 
-# Just run normal server if the data directory is already initialized
-if [ -d "${MYSQL_DATADIR}/mysql" ]; then
-  exec /usr/bin/run-mysqld "$@"
-fi
-
 export MYSQL_RUNNING_AS_SLAVE=1
 
 # Generate the unique 'server-id' for this master
@@ -28,33 +23,35 @@ log_info "The 'slave' server-id is ${MYSQL_SERVER_ID}"
 # pre-init files
 process_extending_files ${APP_DATA}/mysql-pre-init/ ${CONTAINER_SCRIPTS_PATH}/pre-init/
 
-# Initialize MySQL database and wait for the MySQL master to accept
-# connections.
-initialize_database "$@"
-wait_for_mysql_master
+if [ ! -e "${MYSQL_DATADIR}/mysql" ]; then
+  # Initialize MySQL database and wait for the MySQL master to accept
+  # connections.
+  initialize_database "$@"
+  wait_for_mysql_master
 
-# Get binlog file and position from master
-STATUS_INFO=$(mysql --host "$MYSQL_MASTER_SERVICE_NAME" "-u${MYSQL_MASTER_USER}" "-p${MYSQL_MASTER_PASSWORD}" replication -e 'SELECT gtid from replication limit 1\G')
-GTID_VALUE=$(echo "$STATUS_INFO" | grep 'gtid:' | head -n 1 | sed -e 's/^\s*gtid: //')
+  # Get binlog file and position from master
+  STATUS_INFO=$(mysql --host "$MYSQL_MASTER_SERVICE_NAME" "-u${MYSQL_MASTER_USER}" "-p${MYSQL_MASTER_PASSWORD}" replication -e 'SELECT gtid from replication limit 1\G')
+  GTID_VALUE=$(echo "$STATUS_INFO" | grep 'gtid:' | head -n 1 | sed -e 's/^\s*gtid: //')
 
-# checking STATUS_INFO here because empty GTID_VALUE is valid value
-if [ -z "${STATUS_INFO}" ] ; then
-  echo "Could not read GTID value from master"
-  exit 1
-fi
+  # checking STATUS_INFO here because empty GTID_VALUE is valid value
+  if [ -z "${STATUS_INFO}" ] ; then
+    echo "Could not read GTID value from master"
+    exit 1
+  fi
 
-mysql $mysql_flags <<EOSQL
+  mysql $mysql_flags <<EOSQL
   STOP SLAVE;
   SET GLOBAL gtid_slave_pos = "${GTID_VALUE}";
   CHANGE MASTER TO MASTER_HOST='${MYSQL_MASTER_SERVICE_NAME}',MASTER_USER='${MYSQL_MASTER_USER}', MASTER_PASSWORD='${MYSQL_MASTER_PASSWORD}', MASTER_USE_GTID=slave_pos;
   START SLAVE;
 EOSQL
 
-# init files
-process_extending_files ${APP_DATA}/mysql-init/ ${CONTAINER_SCRIPTS_PATH}/init/
+  # init files
+  process_extending_files ${APP_DATA}/mysql-init/ ${CONTAINER_SCRIPTS_PATH}/init/
 
-# Restart the MySQL server with public IP bindings
-shutdown_local_mysql
+  # Restart the MySQL server with public IP bindings
+  shutdown_local_mysql
+fi
 
 unset_env_vars
 log_volume_info $MYSQL_DATADIR
