Make the test version agnostic

diff --git a/10.1/test/run b/10.1/test/run
--- a/10.1/test/run
+++ b/10.1/test/run
@@ -10,7 +10,10 @@ set -o errexit
 set -o nounset
 shopt -s nullglob
 
-IMAGE_NAME=${IMAGE_NAME-centos/mariadb-101-centos7-candidate}
+if [ -e "${IMAGE_NAME:-}" ] ; then
+  echo "Error: IMAGE_NAME must be specified"
+  exit 1
+fi
 
 CIDFILE_DIR=$(mktemp --suffix=mysql_test_cidfiles -d)
 
@@ -370,7 +373,7 @@ function run_tests() {
   create_container $name $envs
   test_connection "$name" "$USER" "$PASS"
   echo "  Testing scl usage"
-  test_scl_usage $name 'mysql --version' '10.1'
+  test_scl_usage $name 'mysql --version' '10.'
   echo "  Testing login accesses"
   local container_ip
   container_ip=$(get_container_ip $name)
